### ISSUE TITLE
You can transfer money between accounts with different currencies

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#230] opened 2023-01-18 11:58 UTC
It is possible to transfer money from one account to another account despite the two accounts having different currencies.

**Comment by nlogozzo** [comment] 2023-01-18 12:01
Duplicate of https://github.com/nlogozzo/NickvisionMoney/issues/144

**Closed by nlogozzo** 2023-01-18 12:01 UTC
