### ISSUE TITLE
Currency code not saved

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#231] opened 2023-01-18 12:10 UTC
The currency code in the account dialog does not seem to get saved.

**Comment by nlogozzo** [comment] 2023-01-18 12:12
Duplicate of https://github.com/nlogozzo/NickvisionMoney/issues/225

**Comment by nlogozzo** [comment] 2023-01-18 12:12
Please look for already opened issues before creating new ones :)

**Closed by nlogozzo** 2023-01-18 12:12 UTC

**Comment by vanillajonathan** [comment] 2023-01-18 12:16
I also experienced the issue with that the **currency symbol** did not get used until I restarted, but I restarted and **currency code** it does still not seem to be persisted.

I think this is a different bug.

**Comment by nlogozzo** [comment] 2023-01-18 12:19
That's also part of #225. 

It's all fixed in #224. Once that gets merged, I'm thinking of releasing a 2023.1.1 bugfix release today.
