### ISSUE TITLE
Add biweekly option to the repeat interval

### ISSUE THREAD

**Issue by DaisyLee2010** [nlogozzo/NickvisionMoney#154] opened 2022-12-31 04:25 UTC
Would be useful for people who get their paycheck every two weeks

**Comment by fsobolev** [comment] 2022-12-31 04:29
Duplicate of #8

**Closed by fsobolev** 2022-12-31 04:29 UTC

**Comment by nlogozzo** [comment] 2023-01-06 18:31
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta3
