### ISSUE TITLE
Groups crashes Denaro

### ISSUE THREAD

**Issue by FelCar11** [nlogozzo/NickvisionMoney#314] opened 2023-02-18 03:27 UTC
Sometimes after creating a group, Denaro crashes, if you add a transaction to those buggy groups and try to edit it, it will either crash sometimes or it will be sent to another group. In the video, I managed to crash Denaro by adding a transaction to one corrupted group.

[Grabación de pantalla desde 2023-02-17 22-02-28.webm](https://user-images.githubusercontent.com/107369720/219828560-5bbe1e57-f2f3-4212-8574-cbc4d9743728.webm)

And here it crashed after trying to edit a transaction in the corrupted group. In fact, it kept crashing everytime I tried to edit it until I deleted the group.

[Grabación de pantalla desde 2023-02-17 21-52-51.webm](https://user-images.githubusercontent.com/107369720/219828941-1b142b53-d4c6-437c-9701-9f7ed945eb7f.webm)

**Comment by nlogozzo** [comment] 2023-02-18 13:48
Could you send me that nmoney file?

**Comment by nlogozzo** [comment] 2023-02-18 15:15
Since you call the groups "corrupted", did you ever use this file on beta/rc versions of Denaro?

**Comment by FelCar11** [comment] 2023-02-18 15:24
Here are the archives, and no, I've only used the version available at Fedora 37 flathub repository.
[archives.zip](https://github.com/nlogozzo/NickvisionMoney/files/10774592/archives.zip)

**Comment by nlogozzo** [comment] 2023-02-22 00:24
This is actually a duplicate of https://github.com/nlogozzo/NickvisionMoney/issues/306 which has been fixed...going to release a stable now so you should have the fix soon.

**Closed by nlogozzo** 2023-02-22 00:24 UTC
Labels: bug

**Comment by nlogozzo** [comment] 2023-02-22 00:43
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.1
